modLoader="javafml" #mandatory
license="All Rights Reserved"
loaderVersion="[36,)" #mandatory (28 is current forge version)
issueTrackerURL="https://github.com/SkyNetCloud/CyberCore_Mod/issues"
logoFile="Logo.png" #optional

[[mods]] #mandatory
modId="cybercore" #mandatory
version="1.16.19042" #mandatory
displayName="CyberCore" #mandatory
authors="SkyNetCloud"
updateJSONURL="https://raw.githubusercontent.com/SkyNetCloud/CyberCore_Mod/1.16.5/update.json" #optional
description='''
A small Tech Mod With a lot being adding when I have the Time :D
'''