modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory (28 is current forge version)
[[mods]] #mandatory
modId="cybercore" #mandatory
version="${file.jarVersion}" #mandatory
displayName="CyberCore" #mandatory
logoFile="Logo.png" #optional
updateJSONURL="https://github.com/SkyNetCloud/CyberCore_Mod/raw/update.json" #optional
description='''
A small Tech Mod
'''

