modLoader="javafml"
license="All Rights Reserved"
loaderVersion="[39,)"
issueTrackerURL="https://github.com/SkyNetCloud/CyberCore_Mod/issues"
logoFile="Logo.png" #optional

[[mods]]
modId="cybercore"
version="3.0.19043"
displayName="CyberCore"
authors="SkyNetCloud"
updateJSONURL="https://raw.githubusercontent.com/SkyNetCloud/CyberCore_Mod/1.18.1/update.json"
description='''
A small Tech Mod With a lot being adding when I have the Time :D
'''